

def save_configuration(configuration, filestr:str, format="xyz", append=False):        
    """ Saves configuration to file.

    Helpful for, e.g., VMD visualization
    This current version only supports the standard xyz-format.

    Example
    -------

    >>> import os
    >>> import rumdpy as rp
    >>> import numpy as np
    >>> conf = rp.Configuration(D=3, N=10)
    >>> rp.tools.save_configuration(configuration=conf, filestr="final.xyz", format="xyz")
    >>> a = np.loadtxt("final.xyz", skiprows=1)
    >>> assert (a==np.c_[conf.ptype, conf['r']]).all(), "Failure in save_configuration"
    >>> os.remove("final.xyz")

    """

    import numpy as np
    append = "a" if append else "w"

    if format=="xyz":
        with open(filestr, append) as f:
            np.savetxt(f, np.c_[configuration.ptype, configuration['r']],
                    header=f"{configuration.N}\n#Position xyz format - generated by rumdpy", comments="")
    else:
        raise ValueError("Format not supported")


