

def save_configuration(configuration, filestr:str, format="xyz", append=False):        
    """
    Saves the current system configuration to file. (Helpful for, e.g., VMD
    visualization)
    
    This version only supports the standard xyz-format
    """

    if format=="xyz":     
        npart = configuration.N     
        
        if append:
            fp =  open(filestr,"a")
        else:
            fp = open(filestr, "w")

        fp.write("%d\n" % (npart))     
        fp.write("Position xyz format - generated by rumdpy\n")     
        for n in range(npart):         
            fp.write("%d %f %f %f\n" % (configuration.ptype[n], configuration['r'][n][0], configuration['r'][n][1], configuration['r'][n][2]))     

        fp.close()

    else:
        raise ValueError("Format not supported")


